apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
  - namespace.yaml
  - bitnami-helm-source.yaml
  - release.yaml
configMapGenerator:
  - name: redis-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml